#Configuration file for BigBrother plugin

#Do not change the interface if you don't know what you are doing. It's good as it is now
interface: 0.0.0.0
port: 25565

network-compression-threshold: 256

#Sets the server description on the server list
motd: "§bPocketMine-MP server using §6§lBigBrother§r§b plugin\n§aConnect to Minecraft: PE servers from PC clients"

#Use Mojang services to authenticate players
online-mode: true

#Automatically authenticate players on SimpleAuth that were authenticated via Mojang servers
online-mode-simpleauth: false

#Action when there is a nick conflict
#kickpe: kicks the Pocket Edition player
#kickpc: kicks the PC player
#kickold: kicks the player that was on the server
#kicknew: kicks the player that is connecting
#none: do nothing, leave it up to PocketMine-MP and other plugins
action-on-conflict: none