name: build
on: push
jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'BigBrotherTeam' }}
    strategy:
      matrix:
        php:
          - 7.3.25
          - 7.4.13

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Rewrite Image Version
        run: sed -i -e "s/FROM php:7/FROM php:${{ matrix.php }}/" Dockerfile

      - name: Login GitHub Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/bigbrotherteam/bigbrother/php:${{ matrix.php }}
            ghcr.io/bigbrotherteam/bigbrother/php:latest

      - name: Push Docker image
        run: docker push ghcr.io/bigbrotherteam/bigbrother/php:${{ matrix.php }}

      - name: Update Latest
        if: matrix.php == '7.4.13'
        run: docker push ghcr.io/bigbrotherteam/bigbrother/php:latest


  build:
    name: build plugin
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: docker
    container:
      image: ghcr.io/bigbrotherteam/bigbrother/php:${{ matrix.php }}
    strategy:
      matrix:
        php:
          - 7.3.25
          - 7.4.13

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: build
        run: |
          composer install
          composer build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ matrix.php == '7.4.13' }}
        with:
          name: BigBrother.phar
          path: build/BigBrother.phar
